### ISSUE TITLE
wrong submenu content on plone4

### ISSUE THREAD

**Issue by toutpt** [mishunov/webcouturier.dropdownmenu#1] opened 2011-05-24 09:43 UTC
I have a default plone install built from the provided buildout.

With the default plone content, 'news' tab list news, events, members as submenu of news. It should list nothing except 'archive'

**Comment by rpatterson** [comment] 2011-07-31 23:27
I can confirm this, both in tests and production.  The culprit is 001fbfc0a7d5d765e5b17a1945a7612e1bd72bc0.

**Comment by rpatterson** [comment] 2011-07-31 23:50
I can also confirm that pull request #5 fixes this.  Can we merge this fork?

**Comment by mishunov** [comment] 2011-08-01 07:47
I have merged the pull request. I didn't have time to check it myself, but if it works, it works. Thanks, JeanMichel and Ross.

**Comment by mishunov** [comment] 2011-08-15 09:42
Hi,

I have re-opened this ticket, since it didn't really work for me properly after the merge. And, the code I saw didn't really do the thing to me. But I have got the idea and made appropriate changes to the code to work properly in the Plone 4 and play nice with the INavigationRoot. Could you, guys, please check the master to make sure things do work properly for you now? 

Thanks for your input.

**Comment by toutpt** [comment] 2011-08-15 19:20
master is working for me. I have just see the bug with INavigationRoot using linguaplone, sorry for that.

**Comment by mishunov** [comment] 2011-08-16 09:59
Great, then I close the issue. Thanks toutpt.

**Closed as completed by mishunov** 2011-08-16 09:59 UTC
